FROM node:22-alpine AS build
 
WORKDIR /app/webapp/frontend
 
COPY webapp/frontend/package*.json ./

RUN npm install
 
COPY webapp/frontend ./

RUN npm run build
 
 
FROM nginx:alpine
 
COPY --from=build /app/webapp/frontend/dist /usr/share/nginx/html
 
EXPOSE 80
 
CMD ["nginx", "-g", "daemon off;"]
 
 
 